os: windows
language: csharp
mono: none

script:
- choco install dotnetcore-sdk
- choco install codecov
- dotnet build
- dotnet test -c Release MarlinToolset.UnitTests/MarlinToolset.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover